"""
One-time script: reads syllables-list.csv and generates a Rust source file
with a compile-time perfect hash map (phf). The generated .rs file contains
no human-readable word strings — words are hashed into bucket structures.

Usage:
    python generate_syllables.py

Reads:  resources/syllables-list.csv
Writes: src/syllable_data.rs
"""

import csv
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
CSV_PATH = os.path.join(SCRIPT_DIR, "resources", "syllables-list.csv")
OUT_PATH = os.path.join(SCRIPT_DIR, "src", "syllable_data.rs")


def main():
    entries = {}
    with open(CSV_PATH, "r", encoding="utf-8") as f:
        reader = csv.reader(f)
        for row in reader:
            if len(row) < 2:
                continue
            word = row[0].strip().lower()
            try:
                count = int(row[1].strip())
            except ValueError:
                continue
            if word:
                entries[word] = count

    print(f"Read {len(entries)} unique words from CSV")

    # Generate a Rust source file with a phf_map
    lines = []
    lines.append("// AUTO-GENERATED by generate_syllables.py — do not edit by hand")
    lines.append("// Source: resources/syllables-list.csv")
    lines.append(f"// {len(entries)} entries")
    lines.append("")
    lines.append("use phf::phf_map;")
    lines.append("")
    lines.append("pub static SYLLABLE_MAP: phf::Map<&'static str, u8> = phf_map! {")

    for word in sorted(entries.keys()):
        count = entries[word]
        # Escape any special chars in the word
        escaped = word.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'    "{escaped}" => {count}u8,')

    lines.append("};")
    lines.append("")

    with open(OUT_PATH, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))

    print(f"Wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
