use crate::db::{self, AppState, FormatPage, FormatProfile};
use crate::ydoc;

use typst::diag::{FileError, FileResult, SourceResult};
use typst::foundations::{Bytes, Datetime};
use typst::layout::PagedDocument;
use typst::syntax::{FileId, Source};
use typst::text::{Font, FontBook};
use typst::utils::LazyHash;
use typst::{Library, LibraryExt};

// Embedded Liberation Serif fonts
static FONT_REGULAR: &[u8] = include_bytes!("../fonts/LiberationSerif-Regular.ttf");
static FONT_BOLD: &[u8] = include_bytes!("../fonts/LiberationSerif-Bold.ttf");
static FONT_ITALIC: &[u8] = include_bytes!("../fonts/LiberationSerif-Italic.ttf");
static FONT_BOLD_ITALIC: &[u8] = include_bytes!("../fonts/LiberationSerif-BoldItalic.ttf");

/// Minimal Typst World implementation with embedded fonts, no filesystem access.
struct IweWorld {
    library: LazyHash<Library>,
    book: LazyHash<FontBook>,
    fonts: Vec<Font>,
    source: Source,
}

impl IweWorld {
    fn new(markup: String) -> Self {
        // Load embedded fonts
        let font_data: Vec<&[u8]> = vec![FONT_REGULAR, FONT_BOLD, FONT_ITALIC, FONT_BOLD_ITALIC];
        let fonts: Vec<Font> = font_data
            .into_iter()
            .filter_map(|data| {
                let bytes = Bytes::new(data.to_vec());
                Font::new(bytes, 0)
            })
            .collect();

        let book = FontBook::from_fonts(fonts.iter());
        let source = Source::detached(markup);

        IweWorld {
            library: LazyHash::new(Library::default()),
            book: LazyHash::new(book),
            fonts,
            source,
        }
    }
}

impl typst::World for IweWorld {
    fn library(&self) -> &LazyHash<Library> {
        &self.library
    }

    fn book(&self) -> &LazyHash<FontBook> {
        &self.book
    }

    fn main(&self) -> FileId {
        self.source.id()
    }

    fn source(&self, id: FileId) -> FileResult<Source> {
        if id == self.source.id() {
            Ok(self.source.clone())
        } else {
            Err(FileError::NotFound(id.vpath().as_rootless_path().into()))
        }
    }

    fn file(&self, id: FileId) -> FileResult<Bytes> {
        Err(FileError::NotFound(id.vpath().as_rootless_path().into()))
    }

    fn font(&self, index: usize) -> Option<Font> {
        self.fonts.get(index).cloned()
    }

    fn today(&self, _offset: Option<i64>) -> Option<Datetime> {
        None
    }
}

// ---- Markup builder ----

/// Escape text for Typst markup — backslash-escape special chars.
fn escape_typst(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    for ch in text.chars() {
        match ch {
            '#' | '$' | '\\' | '*' | '_' | '<' | '>' | '@' | '~' | '`' => {
                out.push('\\');
                out.push(ch);
            }
            _ => out.push(ch),
        }
    }
    out
}

/// Build a Typst markup string for front matter page.
fn build_front_matter_page(page: &FormatPage) -> String {
    let mut out = String::new();
    let title = escape_typst(&page.title);
    let content = escape_typst(&page.content);

    match page.page_role.as_str() {
        "title" => {
            out.push_str("#align(center + horizon)[\n");
            out.push_str(&format!("  #text(size: 24pt, weight: \"bold\")[{}]\n", title));
            if !content.is_empty() {
                out.push_str(&format!("  #v(1em)\n  {}\n", content));
            }
            out.push_str("]\n");
        }
        "copyright" => {
            out.push_str("#set text(size: 8pt)\n");
            out.push_str("#align(bottom)[\n");
            if !content.is_empty() {
                out.push_str(&format!("  {}\n", content));
            } else {
                out.push_str(&format!("  {}\n", title));
            }
            out.push_str("]\n");
        }
        "dedication" => {
            out.push_str("#align(center + horizon)[\n");
            out.push_str("#set text(style: \"italic\")\n");
            if !content.is_empty() {
                out.push_str(&format!("  {}\n", content));
            } else {
                out.push_str(&format!("  {}\n", title));
            }
            out.push_str("]\n");
        }
        "toc" => {
            // TOC is auto-generated by Typst outline
            out.push_str("#outline(title: \"Contents\", depth: 1)\n");
        }
        "half-title" => {
            out.push_str("#align(center + horizon)[\n");
            out.push_str(&format!("  #text(size: 18pt)[{}]\n", title));
            out.push_str("]\n");
        }
        _ => {
            // Generic: centered title + content
            out.push_str("#align(center)[\n");
            out.push_str(&format!("  #text(size: 16pt, weight: \"bold\")[{}]\n", title));
            out.push_str("]\n");
            if !content.is_empty() {
                out.push_str("#v(1em)\n");
                // Render content as paragraphs
                for para in content.split("\\n\\n") {
                    let trimmed = para.trim();
                    if !trimmed.is_empty() {
                        out.push_str(&format!("{}\n\n", trimmed));
                    }
                }
            }
        }
    }

    out
}

/// Build complete Typst markup for the entire book.
fn build_typst_markup(
    profile: &FormatProfile,
    front_pages: &[FormatPage],
    chapters: &[(String, String)], // (title, text with \n\n paragraph breaks)
    back_pages: &[FormatPage],
) -> String {
    let mut doc = String::new();

    // Page setup
    doc.push_str(&format!(
        "#set page(\n  width: {}in,\n  height: {}in,\n  margin: (top: {}in, bottom: {}in, outside: {}in, inside: {}in),\n)\n\n",
        profile.trim_width_in,
        profile.trim_height_in,
        profile.margin_top_in,
        profile.margin_bottom_in,
        profile.margin_outside_in,
        profile.margin_inside_in,
    ));

    // Font and paragraph setup
    let font_name = escape_typst(&profile.font_body);
    doc.push_str(&format!(
        "#set text(font: \"{}\", size: {}pt)\n",
        font_name, profile.font_size_pt,
    ));
    // Convert line spacing multiplier to Typst leading (em units).
    // Typst leading is extra space between lines, not the line-height multiplier.
    // leading = (multiplier - 1) * font_size, expressed in em = (multiplier - 1)
    let leading_em = profile.line_spacing - 1.0;
    doc.push_str(&format!(
        "#set par(leading: {}em, first-line-indent: 1.5em)\n\n",
        leading_em,
    ));

    // ---- Front matter ----
    // Front matter uses roman numeral page numbering and no heading numbering
    if !front_pages.is_empty() {
        doc.push_str("#set page(numbering: \"i\")\n");
        doc.push_str("#counter(page).update(1)\n\n");

        for page in front_pages {
            doc.push_str(&build_front_matter_page(page));
            doc.push_str("#pagebreak()\n\n");
        }
    }

    // ---- Body (chapters) ----
    // Switch to arabic page numbering
    doc.push_str("#set page(numbering: \"1\")\n");
    doc.push_str("#counter(page).update(1)\n\n");

    for (i, (title, text)) in chapters.iter().enumerate() {
        if i > 0 {
            doc.push_str("#pagebreak()\n\n");
        }

        // Chapter heading — centered, no indent for first paragraph after
        let escaped_title = escape_typst(title);
        doc.push_str(&format!(
            "#heading(level: 1, outlined: true)[{}]\n",
            escaped_title,
        ));
        doc.push_str("#v(2em)\n");

        // Paragraphs from extracted text (\n\n separated)
        let paragraphs: Vec<&str> = text.split("\n\n").collect();
        for (pi, para) in paragraphs.iter().enumerate() {
            let trimmed = para.trim();
            if trimmed.is_empty() {
                continue;
            }
            let escaped = escape_typst(trimmed);
            if pi == 0 {
                // First paragraph: no indent
                doc.push_str(&format!("#par(first-line-indent: 0em)[{}]\n\n", escaped));
            } else {
                doc.push_str(&format!("{}\n\n", escaped));
            }
        }
    }

    // ---- Back matter ----
    if !back_pages.is_empty() {
        doc.push_str("#pagebreak()\n\n");
        for page in back_pages {
            doc.push_str(&build_front_matter_page(page));
            doc.push_str("#pagebreak()\n\n");
        }
    }

    // Chapter heading style — centered, no numbering
    // Put this at the top level so it applies to all headings
    let heading_style = format!(
        "#show heading.where(level: 1): it => {{\n  set align(center)\n  set text(size: 16pt, weight: \"regular\")\n  v(3em)\n  it.body\n  v(1em)\n}}\n\n"
    );

    // Prepend heading style after page/font setup
    // Actually, let's insert it at the beginning after the set rules
    format!("{}{}", heading_style, doc)
}

// ---- Compile & SVG render ----

use std::sync::Mutex;
use std::time::Instant;
use serde::Serialize;

fn compile_document(markup: &str) -> Result<PagedDocument, String> {
    let world = IweWorld::new(markup.to_string());
    let warned = typst::compile::<PagedDocument>(&world);
    match warned.output {
        Ok(doc) => Ok(doc),
        Err(diagnostics) => {
            let mut errors = Vec::new();
            for diag in diagnostics {
                errors.push(format!("{:?}", diag.message));
            }
            Err(format!("Typst compilation failed: {}", errors.join("; ")))
        }
    }
}

// ---- Cached document state ----

pub struct FormatState {
    document: Mutex<Option<PagedDocument>>,
}

impl FormatState {
    pub fn new() -> Self {
        FormatState {
            document: Mutex::new(None),
        }
    }
}

// ---- Response types ----

#[derive(Serialize, Clone)]
pub struct CompileTiming {
    pub db_load_ms: f64,
    pub ydoc_extract_ms: f64,
    pub markup_build_ms: f64,
    pub typst_compile_ms: f64,
    pub total_ms: f64,
    pub page_count: usize,
    pub chapter_count: usize,
    pub markup_len: usize,
}

#[derive(Serialize, Clone)]
pub struct CompileResult {
    pub page_count: usize,
    pub timing: CompileTiming,
}


// ---- Tauri commands ----

/// Compile the document and cache it. Returns page count + timing. No SVGs yet.
#[tauri::command]
pub fn compile_preview(
    state: tauri::State<'_, AppState>,
    format_state: tauri::State<'_, FormatState>,
    profile_id: i64,
) -> Result<CompileResult, String> {
    let total_start = Instant::now();

    let guard = state.db.lock().map_err(|e| e.to_string())?;
    let conn = guard.as_ref().ok_or("No project open")?;

    let profile = db::get_format_profile(conn, profile_id)
        .map_err(|e| e.to_string())?
        .ok_or("Profile not found")?;

    if profile.target_type == "ebook" {
        // Clear cached doc
        let mut doc_guard = format_state.document.lock().map_err(|e| e.to_string())?;
        *doc_guard = None;
        return Ok(CompileResult {
            page_count: 0,
            timing: CompileTiming {
                db_load_ms: 0.0, ydoc_extract_ms: 0.0, markup_build_ms: 0.0,
                typst_compile_ms: 0.0, total_ms: 0.0, page_count: 0,
                chapter_count: 0, markup_len: 0,
            },
        });
    }

    // 1. DB load
    let t = Instant::now();
    let format_pages = db::list_format_pages(conn, profile_id).map_err(|e| e.to_string())?;
    let chapters_raw = db::list_chapters(conn).map_err(|e| e.to_string())?;
    let db_load_ms = t.elapsed().as_secs_f64() * 1000.0;

    // 2. Y.Doc text extraction
    let t = Instant::now();
    let mut chapters: Vec<(String, String)> = Vec::new();
    for ch in &chapters_raw {
        let text = ydoc::extract_text_with_breaks_from_bytes(&ch.content);
        chapters.push((ch.title.clone(), text));
    }
    let ydoc_extract_ms = t.elapsed().as_secs_f64() * 1000.0;
    let chapter_count = chapters.len();

    let front: Vec<FormatPage> = format_pages.iter().filter(|p| p.position == "front").cloned().collect();
    let back: Vec<FormatPage> = format_pages.iter().filter(|p| p.position == "back").cloned().collect();

    // 3. Markup generation
    let t = Instant::now();
    let markup = build_typst_markup(&profile, &front, &chapters, &back);
    let markup_build_ms = t.elapsed().as_secs_f64() * 1000.0;
    let markup_len = markup.len();

    // 4. Typst compilation
    let t = Instant::now();
    let document = compile_document(&markup)?;
    let typst_compile_ms = t.elapsed().as_secs_f64() * 1000.0;

    let page_count = document.pages.len();
    let total_ms = total_start.elapsed().as_secs_f64() * 1000.0;

    log::info!(
        "[format] compile: {}ms total | db:{}ms ydoc:{}ms markup:{}ms compile:{}ms | {} pages, {} chapters, {}KB markup",
        total_ms as u32, db_load_ms as u32, ydoc_extract_ms as u32, markup_build_ms as u32,
        typst_compile_ms as u32, page_count, chapter_count, markup_len / 1024,
    );

    // Cache the compiled document
    let mut doc_guard = format_state.document.lock().map_err(|e| e.to_string())?;
    *doc_guard = Some(document);

    Ok(CompileResult {
        page_count,
        timing: CompileTiming {
            db_load_ms,
            ydoc_extract_ms,
            markup_build_ms,
            typst_compile_ms,
            total_ms,
            page_count,
            chapter_count,
            markup_len,
        },
    })
}

/// Export a single page to SVG from the cached document (called by URI protocol handler).
pub fn render_page_svg(format_state: &FormatState, page_index: usize) -> Result<String, String> {
    let doc_guard = format_state.document.lock().map_err(|e| e.to_string())?;
    let document = doc_guard.as_ref().ok_or("No compiled document")?;
    let page = document.pages.get(page_index).ok_or("Page index out of range")?;
    Ok(typst_svg::svg(page))
}
